### ISSUE TITLE
Exceptions should not be used in Objective C

### ISSUE THREAD

**Issue by gnachman** [itod/pegkit#33]
The use of `@throw` is problematic. It prevents you from usefully setting breakpoints on objective-C exceptions because `PKParser` will throw many exceptions as part of its normal operation. A developer must choose between not breaking on exceptions that are actually errors or hitting continue many times during parsing.

**Comment by ThePantsThief** [comment]
Seconded

**Comment by itod** [comment]
This is expected behavior. PEGKit uses exceptions for control flow. I know you are rolling your eyes right now, because everyone "knows" that using exceptions for control flow is the Wrong Way to Do Things.

Well, for most cases that advice ("don't use exceptions for control flow") is, of course, correct. However, PEGKit produces *recursive-descent* parsers with *infinite look-ahead*. When you use recursion to produce infinite look-ahead, you often have to *backtrack up the stack* after attempting an unsuccessful parsing path (in fact, this is happening constantly during parsing).

And the most elegant (perhaps only manageable?) way to control this type of flow is via exceptions.

For the (practical) research behind this theory, see Terence Parr's excellent [Language Implementation Patterns](https://pragprog.com/book/tpdsl/language-implementation-patterns). Parr is the creator of the industry-leading parsing toolkit [ANTLR](http://www.antlr.org/), which is a major influence on PEGKit's design.

![Terence Parr's Slide deck](https://cloud.githubusercontent.com/assets/8112/19653366/e99135e4-99d9-11e6-91fa-ebc17a6c8b7d.png)

There's really no problem with this technique except one. And you've just discovered it. You basically cannot have an "All ObjC Exceptions" breakpoint enabled while your parsing is executing. That sucks, but it can be worked around fairly easily. You'll just have to disable that breakpoint (or all breakpoints) while this part of your app is running.

What I also do to work around this is to sprinkle Assertions all over my code (I think that is good advice anyway), and then I set a breakpoint for: `-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]`. I leave breakpoints enabled, but turn off the "All ObjC Exceptions" breakpoint when dealing with code that parses.

**Comment by gnachman** [comment]
It is fixable without exceptions, although it's a good bit of work. You need to modify the functions' return values to include their failure state as well as their return code, or return exceptional status through an NSError-like mechanism. I was going to give an example, but `-[PKParse parse:]` already does exactly what I was going to show when its `outError` argument is non-nil.

I was trying to use PEGKit in a giant project (hundreds of thousands of lines of code), so systemic changes were out of the question. I started fixing PEGKit as I described above, but it ended up being easier to use a different protocol and cut out PEGKit instead.

**Comment by gnachman** [comment]
I agree that exceptions are more elegant and simple, and it would have been a good choice in Java. In Objective-C, it prevents PEGKit from being useful; it's more like an academic exercise, as it stands. To be sure this is because Apple did a garbage job with handling exceptions in the debugger, but this is out of our control.

**Comment by itod** [comment]
Well, I make my living on a half-dozen apps that all use PEGKit extensively. And I live in the Xcode debugger. So: No, exceptions do not prevent PEGKit from being useful.
